### ISSUE TITLE
Dynamically Rendered Templates

### ISSUE THREAD

**Issue by ojenksdev** [Zodiase/meteor-mdl#11]
I originally posted on the other issue thread. - Here is one of the error messages we are having: 

```
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

**Comment by Zodiase** [comment]
Could you give a code example that I could use to reproduce the error? By this error message I can't really tell what's causing it.

**Comment by Zodiase** [comment]
In fact it's best for you to provide a complete project that contains this error, since other installed packages could also be part of the cause.

**Comment by ojenksdev** [comment]
We have the files on a private repository, but I zipped the complete package so far, - https://drive.google.com/file/d/0BzgJgYHhx56AeEpjdFY3S0I3b2M/view?usp=sharing

**Comment by Zodiase** [comment]
OK...
The cause of the error is the fact that you separated `<div class="mdl-layout__header-row">` and `<header class="mdl-layout__header">` in two templates. Both of them need to be present so that MDL can upgrade them correctly and after that they should not be taken apart or the MDL component may break.

**Comment by Zodiase** [comment]
Oh and also you don't need to call `componentHandler.upgradeAllRegistered()` because this package calls it for you.

**Comment by ojenksdev** [comment]
Ok so should I add the mdl-layout__header-row to all of the templates I build? Or add the `header class="mdl-layout__header"` to my mainLayout template?

**Comment by Zodiase** [comment]
Since it looks like you would have different `mdl-layout` (with and without tab bar) for different routes, either use different layouts for the ones without tab bars and the ones with tab bars, or put the `mdl-layout` inside templates. The goal is to keep the major components of a `mdl-layout` together.

**Comment by ojenksdev** [comment]
It works now! Thanks for the help!
