### ISSUE TITLE
MDL 1.0.3 is out

### ISSUE THREAD

**Issue by victorhooi** [Zodiase/meteor-mdl#13]
Just a headsup that MDL 1.0.3 is out upstream! =)

**Comment by Zodiase** [comment]
@victorhooi Yep saw it and was preparing for updating. :)
But sadly there seems to be a bug in it. I posted the issue here google/material-design-lite#1416. So I'm waiting for the response.

There were quite a lot PRs in this one and I wasn't able to catch all of them. Anything particular interesting to you?

**Comment by Zodiase** [comment]
Updated package to 1.0.3. Available through `meteor update`.
