### ISSUE TITLE
Routeing With tabs does not work

### ISSUE THREAD

**Issue by ghost** [Zodiase/meteor-mdl#15]
Here is a [meteor pad](http://meteorpad.com/pad/bXdqA9zWWTGx9PwvP/zodiase:mdl%20mdl-layout__tab%20is-active%20routeing%20error) showing the issue. You will notice routes are not working at all. The issue again stems from mdl-layout__tab-panel class in particular the way mdl routes to them. you will see this in the error it returns. This renders tabs completely useless if they can't be routes. I am wondering why keep panels in a meteor mdl at all build. They cause problems and are completely useless with iron router.

**Comment by Zodiase** [comment]
@noah2828 Hi there. I don't think you are using the tabs correctly.

More specifically to your example there, you don't have the correct IDs for the tab. You could see in [this meteor pad](http://meteorpad.com/pad/kQcxKtHCityPE5KRN/MDL%20Tab%20Layout) that the tab layout works just fine even with Iron:Router. Or [this one](http://meteorpad.com/pad/PJFGHTGWZSmTsTzdJ/MDL%20Tab%20Layout%20with%20Contents%20in%20templates).

The purpose of having tabbed content is that the sections don't have to visible at all times, but they are still the content of the current page, there is no point in putting the content into different routes.

Perhaps the only problem would be that you can't use `http://app.meteorpad.com/#tab-2` to open the second tab on start up, which you could if it was different route such as `http://app.meteorpad.com/tab-2`. 

The tabs work as intended, maybe not nicely with Iron:Router but the problems you are encountering are caused by incorrect usage. If you find them not meeting your needs you could certainly write your own tabs that work with routes.

**Comment by ghost** [comment]
The tab system works for static sites but when you are loading in new content and using pagination it increases load time and complexity of the the templates. That is why other frame works mainly use routes not tabs.

**Comment by Zodiase** [comment]
You are talking about using tabs for pagination? I don't suppose that's what tabs should do. For tabs, the content of each tab panel stays on the page, just visually hidden. For pagination, each page gets loaded and unloaded. You would want to have your own implementation of tabs for pagination because for now dynamically adding MDL tabs is impossible because all the binding of tabs are done once during upgrading the layout and there is no way downgrading a layout. To add a MDL tab button, you would have to destroy the whole layout and start from the beginning and that is horrible. Unfortunately that's just how MDL is designed for now. Maybe Google will come up with a better design and implementation.

BTW, I managed to create [this meteor pad](http://meteorpad.com/pad/AKhPMYxpJyMCXtQZb/MDL%20Tab%20Layout%20with%20Routing) to show you an example of how to make the tabs work for routes. However as I said, it's not suitable for pagination.

**Comment by Zodiase** [comment]
I added some comments to the meteor pad to better explain it. In that example I still keep all the tab panels on the page to match the behavior of MDL tabs. But you could easily change that to have just the active tab panel on the page.

**Comment by Zodiase** [comment]
FYI I fixed a bug in that example and the tabs should work now.

**Comment by ghost** [comment]
thanks but no I don't mean what you think I mean. I mean because everything loads up but is hidden it increases load time and code complexity especially if you have pagination the in templates you are loading. Where as in bootstrap and others you use a separate router. When using a separate router you get more control over how much data and what data is sent to the client in the form of specifying individual templates to be loaded. Currently using tabs loads all your templates that the tabs route not just the one in use.

**Comment by Zodiase** [comment]
Ok that's workable. Mostly just like what I did in that example, catch the click event and get the enough data from the tab button and update the content (and the url if you want). To satisfy the MDL tab buttons, make their `href`s all point to an irrelevant hidden target and there you go.

**Comment by ghost** [comment]
I created a fork so Routing can work in tabs
