### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by Devuiux** [Zodiase/meteor-mdl#21]
Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
file:C:....meteor\packages\zodiase_mdl\1.0.5\web.browser\material.js

**Comment by Zodiase** [comment]
Which security software reported this?
Here's a malware scan report I got with the file on my computer: https://www.metascan-online.com/#!/results/file/98a48b2fdba349578cd1b0c2afbd7495/regular.
You could also diff the file with [the official MDl library here](https://storage.googleapis.com/code.getmdl.io/1.0.5/material.js) to see if there's anything suspicious. 
If that file is altered in any way, there's probably a malware on your computer that's injecting bad code.
Otherwise, ask your security software to shut up or maybe consider stop using it.

**Comment by Devuiux** [comment]
a security component from Windows 10, but it got the same with the mdl components from https://storage.googleapis.com/code.getmdl.io/1.0.5/mdl-templates.zip
