### ISSUE TITLE
Unable to add dashboard template from getmdl.io

### ISSUE THREAD

**Issue by bwobst** [Zodiase/meteor-mdl#22]
Hi, I'd like to use this dashboard template: http://www.getmdl.io/templates/dashboard/index.html.

When I try to implement it, the interactive elements like the collapsed left drawer and expandable search bar don't work.

I tried breaking out the header, drawer, and main into their own templates.  I also tried creating special templates that pass in the container divs, header content, and script call to material.min.js at the end of the body.

I got this demo working: http://meteorpad.com/pad/of7fgtnve8QDYDBcA/material-design-lite-test in the same environment following the same way I broke out the different components of the page (header, drawer, main) into their own templates as well.

Here's the MeteorPad with my work so far: http://meteorpad.com/pad/dK5W26dxiJA4zb7Bt/MDL%20Troubleshooting

What do you think am I doing wrong?

Thanks,
Brian

**Comment by Zodiase** [comment]
Well... First thing... I think you are not using my package?

**Comment by Zodiase** [comment]
One thing I'd like to note here is that, if you check the code of the layout component [here](https://github.com/google/material-design-lite/blob/v1.0.6/src/layout/layout.js), when the layout component initializes ("upgrades" as Google calls it), it links the `header`, `drawer` and `content` elements right then and there. So I wouldn't suggest splitting them into different templates in any circumstances (in case any part got messed up by Blaze and the linkage breaks). Put them in one single template and only put the content of the `header`, `drawer` and `content` elements in different templates.

**Comment by bwobst** [comment]
I tried using your package, but got the same issue.  That MeteorPad is just an illustration.  Try swapping out the spectrum package for yours.

Something I also tried was wholesale copying all of the `head` and `body` content from that dashboard with Chrome's Inspector, but that didn't work either.

**Comment by Zodiase** [comment]
Alright. It happens that I have a demo of that dashboard template prepared quite a while ago. I'll make a MeteorPad once I dig that out.

I think I'd explain that, most components in MDL rely heavily on JavaScript and they create helper elements and modify properties for you which simplifies the html code you need to write. While the components do their JavaScript work, they left marks on the elements as indicators so they wouldn't try to modify the elements twice. But that also means copying elements from DOM from the inspector wouldn't work since they are not the way the source code is and the components would think the elements are "upgraded", as Google calls it, while they really are not.

**Comment by Zodiase** [comment]
Actually it might be easier this way... Download the repo at commit 20456639b84bf197cc79f23afcbcd9a8a4fba80b [with this link](https://github.com/Zodiase/meteor-mdl/archive/20456639b84bf197cc79f23afcbcd9a8a4fba80b.zip), you should find a `demo` folder, and in it, there's an `iron-router` folder. That is a meteor app folder, so run `meteor` inside it to bring it up running, and you can check the results in the browser. See the source code of that app to learn how it works.

**Comment by bwobst** [comment]
That's working for me.  Thanks @Zodiase!
