### ISSUE TITLE
annoying messages in 1.1.1

### ISSUE THREAD

**Issue by KristerV** [Zodiase/meteor-mdl#31]
Hey, just updated to 1.1.1 - great work. thank you.

But I keep gettings this annoying message on every server refresh:

```
* zodiase:mdl > Enabled with default settings. See documentation for customization options.
* zodiase:mdl > Using settings: { jsLib: { minified: false },
  theme: { primary: 'indigo', accent: 'pink' },
  patches: { autoUpgrade: 'fullUpgrade' },
  verbose: false }
```

I understand I now have a config file, but what commands do I need to disable this message?

**Comment by Zodiase** [comment]
The purpose of having this log is to hint the developers what settings are in effect, especially in the case of mis-configuration. I didn't expect this to annoy anyone since I see this sort of messages quite often in some of the packages, `Kadira` for example, that I use. But in the next release I'll try to implement caching so the message only appears when the settings file is changed. I think that'll make it much less annoying.

**Comment by KristerV** [comment]
most appreciated effort. I debug stuff to the console all the time - any message there is noise.

**Comment by Zodiase** [comment]
I hope you'd be satisfied by the new update `1.1.1_1` I just published. No more annoying logs! :D

**Comment by KristerV** [comment]
yes! Awseome.. thank you. I've been with these logs since and I can't say i've gotten used to it :D
