### ISSUE TITLE
Cached resources are about 40MB large

### ISSUE THREAD

**Issue by JulianaGaibler** [Zodiase/meteor-mdl#33]
I'm using the appcache-package and due to all these .css files, the cached resources are about 40MB large. Thats too high, in any way. I thought this might be just in the development stage, but even when I publish my project with "Meteor Up", it has the same size. How's that and how can I get rid of all these unnecessary files?

**Comment by Zodiase** [comment]
In order to allow dynamically loading theme files based on settings, all those assets have to be added to the package in the package config file for loading at build time, as the current package system limits. So I hope you could see why all 42MBs of `.css` theme files are included. However not all of these files are actually used in the webpage. Actually at most one `.css` file would be used. I'm not sure why that caching package can't be smart enough to only cache those assets are actually being used. But I'll see if I can hide the `.css` assets from it.

**Comment by Zodiase** [comment]
My first attempt managed to reduce the total cached size down to 5.1MB for my test app (in development mode). I suppose that's still not good enough for you, since the `appcache` package still yells at me about going over 5MB and my test app is almost empty. Consider a fully fledged app it's going to exceed a lot more.

After removing unnecessary client side assets, there are still a few critical files left, which is still considerably large, compared to the 5MB limit. For example, the Material Design Icon font files, which is about 0.7MB.

What you could do to further reduce the footprint of this package is by using

``` JavaScript
{
  "jsLib": {
    "minified": true
  }
}
```

in the settings file. This would load the minified MDL JavaScript file provided by MDL team, which could save you 83KB as of the latest release. But I guess that doesn't really matter as in production mode all files are minified.

Also consider checking out this page https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache which says app cache is going to be deprecated and replaced by service workers, and evaluate how much trouble you'd like to get into for using the `appcache` package.

**Comment by Zodiase** [comment]
Upgrade to `zodiase:mdl@1.1.2_2` to see the reduction in client side assets.

**Comment by JulianaGaibler** [comment]
Thank you so much for your effort. In the meantime I switched to some other mdl package and now back. The difference is just 1MB. I'm now at 8.8MB which works fine - although it is above the limit - and I think this is absolutely fine. After all the reason to use the package is to reduce data-usage in the long-term, but 50MB seemed to be a little bit much.
