### ISSUE TITLE
Tabs <a> are not responding to click events in mdl-layout__tab-bar

### ISSUE THREAD

**Issue by polonski** [Zodiase/meteor-mdl#49]
So trying to capture clicks from tabs. normal everyday vanilla stuff. but it's not working

I've messed about trying to replace _mdl-tabs__tab-bar_  with _mdl-tabs__tab-bar_ but it messes up the UI, throws errors etc. It would be great if the tabs from _mdl-layout__tab-bar_ were able to capture click events.

I've put this on github for your ref  https://github.com/polonski/meteor-mdl-tabs

Thanks!

**Comment by wildhart** [comment]
As mentioned in previous bugs (#14), for tabs to work out-of-the-box the entire layout has to be in the same template.  If that's not possible due to dynamic content or different tabs on different routes then you have to use some of your own javascript.

After a bit of messing around, I've managed to get a system working quite well with minimal js, so I thought I'd share the basics here.  Below are snippets of my code which should demonstrate my solution:

(edit: simplified my code)

In this example, assume a route defined with:

```
tabs: team_edit_tabs
body: team_edit
```

Note that in my app some routes/pages have tabs and some don't, so I need to dynamically show/hide the tab-bar.

```
<template name="app_body">
    <div class="mdl-layout mdl-js-layout">
      <header class="mdl-layout__header mdl-layout__header--waterfall {{#if tabs}}mdl-layout--fixed-tabs{{/if}}">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">{{Title}}</span>
        </div>
        <div class="mdl-layout__tab-bar">
          {{> Template.dynamic template=tabs}}
        </div>
      </header>

      <div class="mdl-layout__drawer">
          ...
      </div>

      <main class="mdl-layout__content">
        {{> Template.dynamic template=body}}
      </main>
    </div>
</template>

<template name="team_edit_tabs">
      <!-- these could also be dynamically created -->
      <a href="#users-panel" class="mdl-layout__tab is-active">Users</a>
      <a href="#teams-panel" class="mdl-layout__tab">Teams</a>
</template>

<template name="team_edit">
    <section class="mdl-layout__tab-panel is-active" id="users-panel">
        <div class="page-content"> 
            ....
        </div>
    </section>
    <section class="mdl-layout__tab-panel" id="teams-panel">
        <div class="page-content"> 
            ....
        </div>
    </section>
</template>
```

Then the only javascript required is:

```

Template.app_body.onRendered(function() {
    // fix the tab bar actions since the built-in ones don't work with dynamically rendered tabs
    $(".mdl-layout__tab-bar").on('click','.mdl-layout__tab',function(e){
        // deactivte all tab links and tab content
        $(".mdl-layout__tab.is-active, .mdl-layout__tab-panel.is-active").removeClass("is-active");
        // active correct tab links
        $(e.target).addClass('is-active');
        // active correct tab content
        $($(e.target).attr('href')).addClass('is-active');
    });
});
```

If not all of your routes have tabs then you also need some css:

```
.mdl-layout__header:not(.mdl-layout--fixed-tabs) .mdl-layout__tab-bar-container {
  display:none;
}
```

I hope this helps.

**Comment by polonski** [comment]
Thanks @wildhart !

All I ended up needing was 

```
Template.tabs.onRendered(function () {  

    $(".mdl-layout__tab-bar").on('click','.mdl-layout__tab',function(e){

        $(e.target).addClass('is-active');

    });

});
```

To capture presses from the tabs.

However I can't access template's reactive vars using this way of capturing clicks

so having the reactive var in header template called `titleLabel` can't be accessed like this:

`Template.instance("header").titleLabel.set("Moo");`

How do I access other template innards from the click capture in `onRendered` ?
