### ISSUE TITLE
Getting error in a clean Meteor 1.4 installation trying to install the package in both Windows and Linux

### ISSUE THREAD

**Issue by ALE1VER** [Zodiase/meteor-mdl#54]
meteor add zodiase:mdl
/home/$USER/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-vv1i8n/plugin.build.os/program.json'
    at Error (native)

**Comment by jbelevicius** [comment]
I got the same issue. Running 'meteor update' then 'meteor add zodiase:mdl' again worked.

**Comment by ALE1VER** [comment]
Not for me.

**Comment by ALE1VER** [comment]
it suddenly worked

**Comment by Zodiase** [comment]
@jamc92 Sorry to see you having this issue. I could not reproduce it on my VMs. Doesn't look like something wrong with the package itself either. I've seen this type of error messages (random nonsense thrown by `meteor-promise`) usually caused by `fourseven:scss` package, which this package depends on. But I have no idea exactly why.

@jbelevicius Thanks for helping.

**Comment by ALE1VER** [comment]
Thank you for checking out @Zodiase !
